### ISSUE TITLE
Crash when sending test failures to Runner for Recording

### ISSUE THREAD

**Issue by badrinrs** [cucumber/cucumber-android#103]
I am seeing a crash due to intent data being too large when sending error stacktrace with view details. This would be caused whenever the view is too large or the app has a lot of different tabs with different recycler views.

`2022-08-22 15:59:28.993 31534-31588/com.roku.remote.debug E/AndroidRuntime: FATAL EXCEPTION: Instr: com.roku.remote.test.cucumber.runner.CucumberTestRunner
    Process: com.roku.remote.debug, PID: 31534
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1081416 bytes
        at android.app.ActivityThread.finishInstrumentation(ActivityThread.java:7699)
        at android.app.Instrumentation.finish(Instrumentation.java:270)
        at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:420)
        at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:463)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:452)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2261)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1081416 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:635)
        at android.app.IActivityManager$Stub$Proxy.finishInstrumentation(IActivityManager.java:7314)
        at android.app.ActivityThread.finishInstrumentation(ActivityThread.java:7697)
        at android.app.Instrumentation.finish(Instrumentation.java:270) 
        at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:420) 
        at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:463) 
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:452) 
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2261) `

**Comment by lsuski** [comment]
I'm not sure if this has anything to do with cucumber itself.  This could be the issue with instrumentation as a such which cucumber-android uses

**Comment by badrinrs** [comment]
Opened an issue with android-test: https://github.com/android/android-test/issues/1483
