### ISSUE TITLE
Compose rule not working on composables hosted in an activity

### ISSUE THREAD

**Issue by alexymumo** [cucumber/cucumber-android#128]
### 👓 What did you see?

````
java.lang.IllegalStateException: Test not setup properly. Use a ComposeTestRule in your test to be able to interact with composables
at androidx.compose.ui.test.junit4.ComposeRootRegistry_androidKt.ensureComposeRootRegistryIsSetUp(ComposeRootRegistry.android.kt:254)
at androidx.compose.ui.test.junit4.ComposeRootRegistry_androidKt.waitForComposeRoots(ComposeRootRegistry.android.kt:261)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.waitForIdle(ComposeUiTest.android.kt:334)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$waitForIdle(ComposeUiTest.android.kt:228)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidTestOwner.getRoots(ComposeUiTest.android.kt:529)
at androidx.compose.ui.test.TestContext.getAllSemanticsNodes$ui_test_release(TestOwner.kt:85)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNodes$ui_test_release(SemanticsNodeInteraction.kt:62)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:128)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:79)
at androidx.compose.ui.test.TextActionsKt.getNodeAndFocus(TextActions.kt:108)
at androidx.compose.ui.test.TextActionsKt.getNodeAndFocus$default(TextActions.kt:105)
at androidx.compose.ui.test.TextActionsKt.performTextInput(TextActions.kt:42)

````

### 🔬 How could we reproduce it

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by prudhvir3ddy** [comment]
@alexymumo You need to add the `ComposeRuleHolder` path inside the glue

**Comment by lsuski** [comment]
I assume it works now. I've enhance README on that topic
