### ISSUE TITLE
test runner must be placed under `test` dir if it's the suffix of application id

### ISSUE THREAD

**Issue by AbdElraoufSabri** [cucumber/cucumber-android#19]
If I had the application id**s** as following 
```
  defaultConfig {
    applicationId "io.abdelraouf.learn.cucumber"
    testApplicationId "io.abdelraouf.learn.cucumber.test"
}
```

then the library expects the runner to be under the package `io.abdelraouf.learn.cucumber.test` and I need to set the

`testInstrumentationRunner "io.abdelraouf.learn.cucumber.test.runner.AndroidCucumberTestRunner"`

Is that normal ?

**Comment by lsuski** [comment]
No, the library does not expect runner to be in package `io.abdelraouf.learn.cucumber.test`. Why do you assume that?

**Comment by lsuski** [comment]
https://github.com/cucumber/cucumber-android#using-cucumber-android

**Comment by AbdElraoufSabri** [comment]
When I put the runner otherwise It throws cucumberOptions not found exception.
say:
```
  defaultConfig {
    applicationId "io.abdelraouf.learn.cucumber"
    testApplicationId "io.abdelraouf.learn.cucumber.test"
}
```
and
`testInstrumentationRunner "io.abdelraouf.learn.cucumber.runner.AndroidCucumberTestRunner"` without `test` package before `runner`.
I get the following error:
```
Testing started at 2:11 PM ...

03/11 14:11:42: Launching Test
$ adb push /home/abdelraouf/AndroidStudioProjects/cucumber/app/build/outputs/apk/debug/app-debug.apk /data/local/tmp/io.abdelraouf.learn.cucumber
$ adb shell pm install -t -r "/data/local/tmp/io.abdelraouf.learn.cucumber"
Success
APK installed in 980 ms
$ adb push /home/abdelraouf/AndroidStudioProjects/cucumber/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk /data/local/tmp/io.abdelraouf.learn.cucumber.test
$ adb shell pm install -t -r "/data/local/tmp/io.abdelraouf.learn.cucumber.test"
Success
APK installed in 549 ms
$ adb push /mnt/Data/Development/.gradle/caches/modules-2/files-2.1/androidx.test/orchestrator/1.1.1/7553b6b0848f4ac80a15520d82df2e261f156091/orchestrator-1.1.1.apk /data/local/tmp/androidx.test.orchestrator
$ adb shell pm install -t -r "/data/local/tmp/androidx.test.orchestrator"
Success
APK installed in 238 ms
$ adb push /mnt/Data/Development/.gradle/caches/modules-2/files-2.1/androidx.test.services/test-services/1.1.1/9dd8143d514bccd46ba59db1011d8a8eedf47a3b/test-services-1.1.1.apk /data/local/tmp/androidx.test.services
$ adb shell pm install -t -r "/data/local/tmp/androidx.test.services"
Success
APK installed in 237 ms
Running tests

$ adb shell am instrument -w -r   -e debug false io.abdelraouf.learn.cucumber.test/io.abdelraouf.learn.cucumber.runner.AndroidCucumberTestRunner
Client not ready yet..
Started running tests

cucumber.runtime.CucumberException: No CucumberOptions annotation
at cucumber.runtime.android.CucumberJUnitRunner.createRuntimeOptions(CucumberJUnitRunner.java:294)
at cucumber.runtime.android.CucumberJUnitRunner.<init>(CucumberJUnitRunner.java:100)
at cucumber.runtime.android.CucumberJUnitRunnerBuilder.runnerForClass(CucumberJUnitRunnerBuilder.java:12)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:789)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:543)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:386)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

Tests ran to completion.

```

**Comment by AbdElraoufSabri** [comment]
The usage said and I quote: 
`Create a class in your test package (usually <package name from AndroidManifest>.test`

**Comment by lsuski** [comment]
Read readme carefully. You don't have to put `@CucumberOptions` in runner class. You do this so the runner class have to be in proper package

**Comment by lsuski** [comment]
This is also stated in CukeulatorAndroidJUnitRunner

>  This annotation does not have to placed in runner class

**Comment by AbdElraoufSabri** [comment]
Okay, But why the cucumber options need to be in a class `<package name from AndroidManifest>.test` It doesn't work otherwise

**Comment by lsuski** [comment]
Because it has to be taken from somewhere. `<package name from AndroidManifest>.test` is taken from `Cotnext.getPackageName()`

**Comment by AbdElraoufSabri** [comment]
Thanks alot for your help.
