### ISSUE TITLE
Cucumber sample failure on Android 4

### ISSUE THREAD

**Issue by Elvis10ten** [cucumber/cucumber-android#21]
The sample works fine on newer devices.

But on Android 4, it fails with this error:

`
java.lang.NoClassDefFoundError: java.util.Objects
at io.cucumber.core.model.GluePath.parse(GluePath.java:32)
at cucumber.runtime.android.CucumberJUnitRunner.createRuntimeOptions(CucumberJUnitRunner.java:286)
at cucumber.runtime.android.CucumberJUnitRunner.<init>(CucumberJUnitRunner.java:100)
at cucumber.runtime.android.CucumberJUnitRunnerBuilder.runnerForClass(CucumberJUnitRunnerBuilder.java:12)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:789)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:543)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:386)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)
`

**Comment by Elvis10ten** [comment]
Some investigating leads me to the GluePath in the cucumber-core library using the Objects class which is not available on pre Android 19 devices.

`
Objects.requireNonNull(gluePath, "gluePath may not be null");
`

**Comment by lsuski** [comment]
It seems that cucumber require Java 1.7 and Android 19. Min sdk is still at 14 because it will cause compile errors for apps with min sdk <19. However tests should be run from api 19. I'll add this to README.

**Comment by n-belokopytov** [comment]
@lsuski I was wondering here - is the line in question the only reason for compilation failure? I could open a PR with the implementation of that method, so that Cucumber 4 is still backwards compatible with older devices. We would like to have these tests still functioning since we have many clients using older devices and breaking their experience will be expensive for our company.

**Comment by lsuski** [comment]
I can't answer that precisely but if cucumber 4 is from java 1.7 there could be more incompatible places. To make all this work cucumber-core would have to have java 1.6 target again because someone could add some code in future which will be incompatible again. You have those options in my opinion:
1. Stick with cucumber 3
2. Fork cucumber repo and keep compatible copy for your purpose
3. Run tests on api 19 - depending on your project there shouldn't be much difference on older devices but you risk some corner edge cases errors.

**Comment by mpkorstanje** [comment]
I would concur with @lsuski's  analysis.

As time goes on Cucumber v4 will see more and more Java 7 features used and Cucumber v5 will target 1.8. This doesn't seem unreasonable as Java 6 was EOLed in April 2013 and Java 7 in April 2015.

**Comment by n-belokopytov** [comment]
@mpkorstanje alright, makes sense, thanks for the heads up. For your consideration - Android platform will not support the full set of features of Java 8 in the near future and probably never will, since it's now Kotlin focused.

**Comment by mpkorstanje** [comment]
That is unfortunate. 

From a practical perspective: Android accounts for only a small fraction of cucumbers usage and aside from @lsuski there have been very few contributions made back to cucumber. At the same time Android does take up a disproportionate amount of time. So I can't really justify that effort.

Additionally Cucumber is an opensource framework developed primarily by unpaid volunteers. This means that any non-trivial barrier to entry will consume peoples time needlessly or put them off from contributing all together.

As such I'd like to at least keep up with a semi-recent version of java.
