### ISSUE TITLE
Cucumber + Android x + Custom Instrumentation = failure to run the tests. 

### ISSUE THREAD

**Issue by thrlr123** [cucumber/cucumber-android#22]
I am facing the exact situation mentioned in here:
https://stackoverflow.com/questions/54832425/android-cucumber-test-running-failed

Looks like AndroidJUnitRunner is somehow interfering with CustomInstrmentationRunner. 
Here is the error:
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).

My project looks exactly like the one in the sample mentioned in the StackOverflow link above

**Comment by lsuski** [comment]
Configuration posted in this SO link is wrong. It uses old Cucumber version, runner inherits drom AJUR which is incompatible and there is unnecessary RunWith annotation. Read Readme, use Cucumber 4.2.5, check sample again.

**Comment by thrlr123** [comment]
Makes sense. Thank you @lsuski 
Also, looks like CucumberInstrumentationCore is gone in the runner, don't we need it anymore?

**Comment by lsuski** [comment]
No we don't, since 4.2.4 there is new runner which you can use directly or inherit from it. It is compatible with AndroidJunit4Runner

**Comment by thrlr123** [comment]
@lsuski 

I changed everything according to your suggestion but I am still seeing this error:
<?xml version='1.0' encoding='UTF-8' ?>
<testsuite name="com.android.builder.testing.ConnectedDevice" tests="1" failures="1" errors="0" skipped="0" time="5.853" timestamp="2019-03-21T21:55:24" hostname="localhost">
  <properties>
    <property name="device" value="Pixel - 9" />
    <property name="flavor" value="EXAMPLE" />
    <property name="project" value="app" />
  </properties>
  <testcase name="No tests found." classname="com.android.builder.testing.ConnectedDevice" time="0.0">
    <failure>No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack &#64;Test annotations).</failure>
  </testcase>
</testsuite>

**Comment by thrlr123** [comment]
I have something like this in my build.gradle:
defaultConfig:
 testApplicationId "com.abc.xyz.espressoTests"
        testInstrumentationRunner getInstrumentation()

testOptions {
        if (orchestrator) {
            execution "ANDROIDX_TEST_ORCHESTRATOR"
        }
        unitTests {
            includeAndroidResources = true
        }
    }

def getInstrumentation() {
    project.hasProperty('cucumber') ? 'com.abc.xyz.espressoTests.CucumberTestRunner' :
            'androidx.test.runner.AndroidJUnitRunner'
}

Dp you think that ORCHESTRATOR / testOptions might be the issue? @lsuski

**Comment by thrlr123** [comment]
The command below as per your read.me is not returning the desired results 

adb shell pm list instrumentation
instrumentation:androidx.test.orchestrator/.AndroidTestOrchestrator (target=androidx.test.orchestrator)
instrumentation:com.abc.xyz.espressoTests/androidx.test.runner.AndroidJUnitRunner (target=com.abc.xyz)

I don't see my custom instrumentation runner at all.

**Comment by lsuski** [comment]
You are running tests with `instrumentation:com.abc.xyz.espressoTests/androidx.test.runner.AndroidJUnitRunner` - it won't work  if you have cucumber tests. According to your build.gradle you should pass `cucumber` option to build. You can use orchestrator with cucumber

**Comment by lsuski** [comment]
You have to use `CucumberAndroidJUnitRunner` either directly or by inheritance

**Comment by thrlr123** [comment]
With the following build.gradle I am getting this error when I run the tests using  
**./gradlew connectedCheck -Pcucumber -Ptags="@jira_1234"**

```
defaultConfig:
testApplicationId "com.abc.xyz.espressoTests"
testInstrumentationRunner **getInstrumentation()**

testOptions {
if (orchestrator) {
execution "ANDROIDX_TEST_ORCHESTRATOR"
}
unitTests {
includeAndroidResources = true
}
}

def getInstrumentation() {
project.hasProperty('cucumber') ? 'com.abc.xyz.espressoTests.CucumberTestRunner' :
'androidx.test.runner.AndroidJUnitRunner'
}
```

Error:
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations). 

Notice that I am using cucumber tag with my gradle connectedCheck command 


I changed it to:

```
defaultConfig:
testApplicationId "com.abc.xyz.espressoTests"
testInstrumentationRunner **"com.abc.xyz.espressoTests.CucumberTestRunner"**

testOptions {
if (orchestrator) {
execution "ANDROIDX_TEST_ORCHESTRATOR"
}
unitTests {
includeAndroidResources = true
}
}
```

I am getting the same error as above even though my CucumberTestRunner inherits from CucumberAndroidJUnitRunner.

Then I changed it to:

```
  testApplicationId "com.arubanetworks.appviewer.espressoTests"
        testInstrumentationRunner **'cucumber.api.android.CucumberAndroidJUnitRunner'**
```

**Now my tests are running but I cannot use my CustomInstrumentation** anymore. I want to use my custom CucumberTestRunner for cucumber, how do I do that? Do I have to mention it in the Manifest too? @lsuski

**Comment by lsuski** [comment]
Did you check logcat? You should debug `cucumber.runtime.android.CucumberJUnitRunner`, maybe it can't find any feature or you have syntax error in features. I can't do anything at this moment because it is not a bug in cucumber-android. I'm using it in many projects and it works, cukeculator also works. You can share your project and I can check if you don't mind

**Comment by thrlr123** [comment]
You are right...there is some crash in the custom runner onCreate method... at super.onCreate(bundle)

2019-03-22 08:26:24.213 2234-2234/com.abc.xyz E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abc.xyz, PID: 2234
    java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.abc.xyz.espressoTests/com.abc.xyz.CucumberTestRunner}: java.lang.RuntimeException: Instrumentation already started
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5868)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Instrumentation already started
        at android.app.Instrumentation.start(Instrumentation.java:157)
        at androidx.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:306)
        at cucumber.api.android.CucumberAndroidJUnitRunner.onCreate(CucumberAndroidJUnitRunner.java:33)
        at com.abc.xyz.espressoTests.CucumberTestRunner.onCreate(CucumberTestRunner.java:71)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5863)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-03-22 08:26:24.218 2234-2234/com.abc.xyz E/InstrumentationResultPrinter: Failed to mark test No Tests as finished after process crash
2019-03-22 08:26:24.220 2234-2234/com.abc.xyz E/MonitoringInstr: Exception encountered by: Thread[main,5,main]. Dumping thread state to outputs and pining for the fjords.
    java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.abc.xyz.espressoTests/com.abc.xyz.espressoTests.CucumberTestRunner}: java.lang.RuntimeException: Instrumentation already started
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5868)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Instrumentation already started
        at android.app.Instrumentation.start(Instrumentation.java:157)
        at androidx.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:306)
        at cucumber.api.android.CucumberAndroidJUnitRunner.onCreate(CucumberAndroidJUnitRunner.java:33)
        at com.abc.xyz.espressoTests.CucumberTestRunner.onCreate(CucumberTestRunner.java:71)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5863)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-03-22 08:26:24.229 2234-2234/com.abc.xyz E/THREAD_STATE:   Thread[Profile Saver,5,system]
    
      Thread[Jit thread pool worker thread 0,5,main]
    
      Thread[Binder:2234_3,5,main]
    
      Thread[Binder:2234_2,5,main]
    
      Thread[Instr: com.abc.xyz.espressoTests.CucumberTestRunner,5,main]
        java.lang.Object.wait(Native Method)
        android.app.Instrumentation$Idler.waitForIdle(Instrumentation.java:2231)
        android.app.Instrumentation.waitForIdleSync(Instrumentation.java:396)
        com.abc.xyz.espressoTests.CucumberTestRunner.onStart(CucumberTestRunner.java:131)
        android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
      Thread[main,5,main]
        dalvik.system.VMStack.getThreadStackTrace(Native Method)
        java.lang.Thread.getStackTrace(Thread.java:1538)
        java.lang.Thread.getAllStackTraces(Thread.java:1588)
        androidx.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:643)
        androidx.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:638)
        androidx.test.runner.MonitoringInstrumentation.onException(MonitoringInstrumentation.java:632)
        androidx.test.runner.AndroidJUnitRunner.onException(AndroidJUnitRunner.java:522)
        androidx.test.runner.MonitoringInstrumentation$3.uncaughtException(MonitoringInstrumentation.java:268)
        java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
    
      Thread[FinalizerDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Object.wait(Object.java:422)
        java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
        java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
        java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
        java.lang.Daemons$Daemon.run(Daemons.java:103)
        java.lang.Thread.run(Thread.java:764)
    
      Thread[Binder:2234_1,5,main]
    
      Thread[Signal Catcher,5,system]
    
      Thread[ReferenceQueueDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
        java.lang.Daemons$Daemon.run(Daemons.java:103)
        java.lang.Thread.run(Thread.java:764)
    
      Thread[HeapTaskDaemon,5,system]
    
      Thread[FinalizerWatchdogDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:297)
        java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:277)
        java.lang.Daemons$Daemon.run(Daemons.java:103)
        java.lang.Thread.run(Thread.java:764)
2019-03-22 08:26:24.229 2234-2234/? E/MonitoringInstr: Dying now...
2019-03-22 08:26:24.229 2234-2234/? W/MonitoringInstr: Invoking uncaught exception handler androidx.test.runner.MonitoringInstrumentation$3@5cb33dc (a class androidx.test.runner.MonitoringInstrumentation$3)
2019-03-22 08:26:24.233 2234-2234/? E/InstrumentationResultPrinter: Failed to mark test No Tests as finished after process crash
2019-03-22 08:26:24.234 2234-2234/? E/MonitoringInstr: Exception encountered by: Thread[main,5,main]. Dumping thread state to outputs and pining for the fjords.
    java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.abc.xyz.espressoTests/com.abc.xyz.espressoTests.CucumberTestRunner}: java.lang.RuntimeException: Instrumentation already started
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5868)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Instrumentation already started
        at android.app.Instrumentation.start(Instrumentation.java:157)
        at androidx.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:306)
        at cucumber.api.android.CucumberAndroidJUnitRunner.onCreate(CucumberAndroidJUnitRunner.java:33)
        at com.abc.xyz.espressoTests.CucumberTestRunner.onCreate(CucumberTestRunner.java:71)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5863)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-03-22 08:26:24.238 2234-2234/? E/THREAD_STATE:   Thread[Profile Saver,5,system]
    
      Thread[Jit thread pool worker thread 0,5,main]
    
      Thread[Binder:2234_3,5,main]
    
      Thread[Binder:2234_2,5,main]
    
      Thread[Instr: com.abc.xyz.espressoTests.CucumberTestRunner,5,main]
        java.lang.Object.wait(Native Method)
        android.app.Instrumentation$Idler.waitForIdle(Instrumentation.java:2231)
        android.app.Instrumentation.waitForIdleSync(Instrumentation.java:396)
        com.abc.xyz.espressoTests.CucumberTestRunner.onStart(CucumberTestRunner.java:131)
        android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
      Thread[main,5,main]
        dalvik.system.VMStack.getThreadStackTrace(Native Method)
        java.lang.Thread.getStackTrace(Thread.java:1538)
        java.lang.Thread.getAllStackTraces(Thread.java:1588)
        androidx.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:643)
        androidx.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:638)
        androidx.test.runner.MonitoringInstrumentation.onException(MonitoringInstrumentation.java:632)
        androidx.test.runner.AndroidJUnitRunner.onException(AndroidJUnitRunner.java:522)
        androidx.test.runner.MonitoringInstrumentation$3.uncaughtException(MonitoringInstrumentation.java:268)
        androidx.test.runner.MonitoringInstrumentation$3.uncaughtException(MonitoringInstrumentation.java:275)
        java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
    
      Thread[FinalizerDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Object.wait(Object.java:422)
        java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
        java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
        java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
        java.lang.Daemons$Daemon.run(Daemons.java:103)
        java.lang.Thread.run(Thread.java:764)
    
      Thread[Binder:2234_1,5,main]
    
      Thread[Signal Catcher,5,system]
    
      Thread[ReferenceQueueDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
        java.lang.Daemons$Daemon.run(Daemons.java:103)
        java.lang.Thread.run(Thread.java:764)
    
      Thread[HeapTaskDaemon,5,system]
    
      Thread[FinalizerWatchdogDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:297)
        java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:277)
        java.lang.Daemons$Daemon.run(Daemons.java:103)
        java.lang.Thread.run(Thread.java:764)
2019-03-22 08:26:24.238 2234-2234/? E/MonitoringInstr: Dying now...

**Comment by thrlr123** [comment]
Looks like I was using super.onCreate(bundle); twice, once at the beginning and again at end :|

**Comment by thrlr123** [comment]
Now, I am seeing this error:
Test running failed: Unable to find instrumentation target package: com.abc.xyz. onError: commandError=true message=INSTRUMENTATION_FAILED: com.abc.xyz.espressoTests/com.abc.xyz.espressoTests.CucumberTestRunner

**Comment by lsuski** [comment]
This is build failure or stacktrace in logcat? If stacktrace then post full one

**Comment by thrlr123** [comment]
The culprit was 
 ```
   @Override
    public void onStart() {
        waitForIdleSync();
       // mInstrumentationCore.start();
    }
```
once I removed it from the custom runner class, it worked fine.
Thanks for looking into it. 

@lsuski 
I have one more question though...
I have @Before annotation and some code in there and @After annotation and some code in custom runner...looks like this is not getting set at all...scenario details are being null...how do I apply these to each test scenario in the feature file? 

```
    @After
    public void clear(Scenario scenario) throws Throwable {
        Log.i("clear", "***************************************I am in After method************************");
        Log.i("Scenario Name: ", scenario.getName());
        Log.i("Scenario Status: ", scenario.getStatus().toString());
        scenario.write("Data used : " + Data.get());
        ConfigStatus.saveScreenShotOnFailure(scenario);
        File screenshot = ConfigStatus.getScreenShotFile();

        if (scenario.isFailed()) {
            if (Config.isTakeScreenShotEnabled() && screenshot != null) {
                InputStream screenshotStream = new FileInputStream(screenshot);
                byte[] byteArray = new byte[(int) screenshot.length()];
                screenshotStream.read(byteArray);
                scenario.embed(byteArray, "image/jpeg");
                //Deleting screenshot after storing in cucumber.json
                screenshotStream.close();
            }
        }
        if (screenshot != null) {
            if (screenshot.exists()) {
                screenshot.delete();
                ConfigStatus.setScreenShotFile(null);
            }
        }
    }

    @Before
    public void setup(Scenario scenario) throws Throwable {
        Log.i("setup", "***************************************I am in Before method************************");
        IdlingPolicies.setMasterPolicyTimeout(
                1000 * 60, TimeUnit.MILLISECONDS);
        IdlingPolicies.setIdlingResourceTimeout(
                1000 * 60, TimeUnit.MILLISECONDS);

        System.out.println("Starting - " + scenario.getName());
        Log.d("scenarioValue", scenario.toString());
        setFailureHandler(new CustomFailureHandler(ApplicationProvider.getApplicationContext()));
        Config.setTestCaseId(ConfigStatus.getTestCaseFromScenario(scenario));
        Log.d("scenarioTCI", ConfigStatus.getTestCaseFromScenario(scenario));
        Config.setScenarioName("Continue button is enabled");
        Log.d("scenarioTN", scenario.getName());
        ConfigStatus.setTakeScreenshot(true);
    }

```

**Comment by lsuski** [comment]
1. Are these cucumber annotations or junit counterparts?
2. Are those methods invoked but with null scenario?

**Comment by thrlr123** [comment]
1. They are Cucumber annotations
2. they are not invoked at all

**Comment by thrlr123** [comment]
Having cucumber hooks in custom instrumentation used to work earlier. I got it to work now by moving the cucumber hooks to a separate class and giving that path in glue in the instrumentation and cucumberTestCase.

**Comment by lsuski** [comment]
Hooks need to be in glue path. Your instrumentation does not need to be. Hooks are created and managed by picocontainer or another ObjectFactory so it is not goog idea to put them in instrumentation which in turn is managed by android

**Comment by thrlr123** [comment]
Thanks for the explanation. Got everything to work.
