### ISSUE TITLE
cucumber.runtime.android.MissingStepDefinitionError

### ISSUE THREAD

**Issue by Segismundo** [cucumber/cucumber-android#26]
cucumber.runtime.android.MissingStepDefinitionError:

@Then("^We see an activity Screen$")
public void we_see_an_activity_Screen() throws Throwable {
// Write code here that turns the phrase above into concrete actions
throw new PendingException();
}

at cucumber.runtime.android.AndroidInstrumentationReporter.endOfScenarioLifeCycle(AndroidInstrumentationReporter.java:153)
at java.lang.reflect.Method.invoke(Native Method)
at cucumber.runtime.Utils$1.call(Utils.java:40)
at cucumber.runtime.Timeout.timeout(Timeout.java:16)
at cucumber.runtime.Utils.invoke(Utils.java:34)
at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy3.endOfScenarioLifeCycle(Unknown Source)
at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:47)
at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
at cucumber.runtime.android.CucumberExecutor.execute(CucumberExecutor.java:112)
at cucumber.api.android.CucumberInstrumentationCore.start(CucumberInstrumentationCore.java:88)
at spaceinvaders.test.Instrumentation.onStart(Instrumentation.java:35)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2337)

Feature file:
Feature: UH from SpaceInvaders application

  Background:
    Given We open the app

  @UserStories-feature
  Scenario: Open a game
    When We start the game
    Then We see an activity Screen

steps definition:
public class UserStoriesDef {

    private MainActivity mainActivity;
    private GameView view;
    private int fleetSize;
    private int points;

    @Rule
    public ActivityTestRule<MainActivity> activityTestRule = new ActivityTestRule<>(MainActivity.class);

    private Activity activity;

    @Before("@UserStories-feature")
    public void setup() {
        activityTestRule.launchActivity(new Intent());
        activity = activityTestRule.getActivity();
    }

    @After("@UserStories-feature")
    public void tearDown() {
        activityTestRule.finishActivity();
    }

    @Given("^We open the app$")
    public void weOpenTheApp() {
        mainActivity = new MainActivity();
        view = mainActivity.getGameView();
    }

    @When("^We start the game$")
    public void weStartTheGame() {
        onView(isDisplayed()).perform(click());
        fleetSize = view.getInvaderSpaceFleet().getInvaderSpaceShips().size();
        points = view.getScoreValue();
    }

    @Then("^We see an activity Screen$")
    public void weSeeAnActivityScreen() {
        int state = view.getGameState();
        assertEquals(2, state);
    }

run cucumber with:
@CucumberOptions(
        features = "features",
        glue = "spaceinvaders.test")
public class Instrumentation extends MonitoringInstrumentation {

    private final CucumberInstrumentationCore instrumentationCore = new CucumberInstrumentationCore(this);

    @Override
    public void onCreate(Bundle arguments) {
        super.onCreate(arguments);

        String tags = BuildConfig.TEST_TAGS;
        if (!tags.isEmpty()) {
            arguments.putString("tags", tags.replaceAll(",", "--").replaceAll("\\s",""));
        }

        instrumentationCore.create(arguments);
        start();
    }

    @Override
    public void onStart() {
        super.onStart();
        waitForIdleSync();
        instrumentationCore.start();
    }
}

Why does it just mark that step as not done?

**Comment by Segismundo** [comment]
the repository where we work is https://github.com/Segismundo/Calidad-Software-Junio
branch gherkin

**Comment by lsuski** [comment]
Check logcat for any stacktrace or logs and use newest cucumber-android 4.3.0
