### ISSUE TITLE
cucumber.runtime.CucumberException: No CucumberOptions annotation thrown when @CucumberOptions provided

### ISSUE THREAD

**Issue by jwinwood** [cucumber/cucumber-android#31]
I am getting this error when trying to run cucumber tests using cucumber-android version 4.3.1:
`cucumber.runtime.CucumberException: No CucumberOptions annotation
at cucumber.runtime.android.CucumberJUnitRunner.createRuntimeOptions(CucumberJUnitRunner.java:297)
at cucumber.runtime.android.CucumberJUnitRunner.<init>(CucumberJUnitRunner.java:102)
at cucumber.runtime.android.CucumberJUnitRunnerBuilder.runnerForClass(CucumberJUnitRunnerBuilder.java:12)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)`

In my `app/gradle.build` file I have these set:

`
testApplicationId "com.example.acceptancetestingexample.test"
testInstrumentationRunner "cucumber.api.android.CucumberAndroidJUnitRunner"
`

And I have this class defined for the `@CucumberOptions`:

`
@CucumberOptions(
    glue = ["com.example.acceptancetestingexample.test.LoginDetailsSteps"],
    features = ["/AcceptanceTestingExample/app/src/androidTest/resources"],
    plugin = ["pretty"])
class RunAcceptanceTests
`

**Comment by jwinwood** [comment]
Okay so after debugging the application and where the exception was being thrown, I was using `import io.cucumber.junit.CucumberOptions` however, cucumber-android was looking for `cucumber.api.CucumberOptions`. Is there any plans to update this?

**Comment by mpkorstanje** [comment]
Please bear in mind that this project is almost entirely developed by volunteers. You may want to consider sending a pull request.

**Comment by lsuski** [comment]
If you have cucumber-android 4.3.1 there is no way to import `io.cucumber.junit.CucumberOptions` without compilation failure because this was introduced in cucumber 4.5.0. Do you have additional dependency to any of cucumber modules, except `cucumber-picocontainer`? If so then you should remove it or use the same version for all modules. You don't need to include cucumber-junit/java
