### ISSUE TITLE
No CucumberOptions Annotation

### ISSUE THREAD

**Issue by marcokenata-1** [cucumber/cucumber-android#40]
I ecountered into this error when I wanted to run my test in several build flavors, while in the other build flavors I didn't have this error.

cucumber.runtime.CucumberException: No CucumberOptions annotation at cucumber.runtime.android.CucumberJUnitRunner.createRuntimeOptions(CucumberJUnitRunner.java:300)
at cucumber.runtime.android.CucumberJUnitRunner.<init>(CucumberJUnitRunner.java:102)
at cucumber.runtime.android.CucumberJUnitRunnerBuilder.runnerForClass(CucumberJUnitRunnerBuilder.java:12)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

Can you guys please help me

**Comment by rhavran** [comment]
Hi, @marcokenata-1, is your issue resolved? If not, then could you provide more details like Gradle build configs?

**Comment by lsuski** [comment]
Usually problems with CucumberOptions come from invalid packge of clas which has this annotation. If you have 2 flavours then they can have different testApplicationId. `@CucumberOptions` have to be placed in class which resides in package==testApplicationId, so for 2 flavours with e.g
```
flavour1.testApplicationId = "com.example.test"
flavour2.testApplicationId = "com.flavour.example.test"
```
you need to have 2 class in each of those packages
