### ISSUE TITLE
IllegalArgumentException: "Unknown pattern character 'X'" on API Level < 24

### ISSUE THREAD

**Issue by jporombka** [cucumber/cucumber-android#45]
When starting instrumented tests on devices with API < 24 an IllegalArgumentException gets thrown. As described in https://stackoverflow.com/questions/44588429/unknown-pattern-character-x-when-using-simpledateformat/44588864, the format specifier 'X' is available only from API Level >= 24

build.gradle dependencies:
- cucumber-android 4.4.0
- cucumber-java8

Stacktrace:

`E/TestRunner: java.lang.IllegalArgumentException: Unknown pattern character 'X'
        at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
        at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:258)
        at cucumber.runtime.formatter.JSONFormatter.getDateTimeFromTimeStamp(JSONFormatter.java:392)
        at cucumber.runtime.formatter.JSONFormatter.createTestCase(JSONFormatter.java:197)
        at cucumber.runtime.formatter.JSONFormatter.handleTestCaseStarted(JSONFormatter.java:125)
        at cucumber.runtime.formatter.JSONFormatter.access$100(JSONFormatter.java:42)
        at cucumber.runtime.formatter.JSONFormatter$2.receive(JSONFormatter.java:64)
        at cucumber.runtime.formatter.JSONFormatter$2.receive(JSONFormatter.java:61)
        at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
        at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)
        at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)
        at cucumber.runner.ThreadLocalRunnerSupplier$SynchronizedEventBus.send(ThreadLocalRunnerSupplier.java:93)
        at cucumber.runner.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:61)
        at cucumber.runner.TestCase.run(TestCase.java:38)
        at cucumber.runner.Runner.runPickle(Runner.java:50)
        at cucumber.runtime.junit.AndroidPickleRunner.run(AndroidPickleRunner.java:45)
        at cucumber.runtime.junit.AndroidFeatureRunner.runChild(AndroidFeatureRunner.java:41)
        at cucumber.runtime.junit.AndroidFeatureRunner.runChild(AndroidFeatureRunner.java:12)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at cucumber.runtime.android.CucumberJUnitRunner.runChild(CucumberJUnitRunner.java:266)
        at cucumber.runtime.android.CucumberJUnitRunner.runChild(CucumberJUnitRunner.java:71)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at cucumber.runtime.android.CucumberJUnitRunner$2.evaluate(CucumberJUnitRunner.java:324)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
    ----- end exception -----`

**Comment by lsuski** [comment]
Do you use cucumber-java8 as additional dependency? Try without it. AFAIK this is issue with JsonFormatter - you shouldn't use it if running on api below 24

**Comment by badrinrs** [comment]
I am not using cucumber-java8. I am using cucumber-android and cucumber-picocontainer dependencies.  Can you please advise how I can fix the same.

**Comment by lsuski** [comment]
Don't use JsonFormatter as it is using unsupported format specifier.

**Comment by topher-h** [comment]
I believe the problem comes from the cucumber-java dependency, more specifically from [this line](https://github.com/cucumber/cucumber-jvm/blob/9c957514e1b466b18c0a13186d308d913d1ad4a4/core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java#L395).

I think you can avoid this for the moment by not specifying a path for the built in JSON formatter when testing on those API levels. If you really need JSON reports as well though, you could implement a [custom one](https://cucumber.io/docs/cucumber/reporting/#custom-formatters) based on JSONFormatter that has a safe format string.

**Comment by maxbetton** [comment]
Hello everyone, I created a custom formatter as indicated above. 
`@CucumberOptions(
    plugin = [
        "pretty",
        "junit:/sdcard/Android/data/" + BuildConfig.APPLICATION_ID + "/files/junit.xml",
        "com.common.customJSONFormatter.JSONFormatter:/sdcard/Android/data/" + BuildConfig.APPLICATION_ID + "/files/report.json"],`
But I have an IllegalAccessException : 
`cucumber.runtime.CucumberException: java.lang.IllegalAccessException: java.lang.Class<com.common.customJSONFormatter.JSONFormatter> is not accessible from java.lang.Class<cucumber.runtime.formatter.PluginFactory>
at cucumber.runtime.formatter.PluginFactory.newInstance(PluginFactory.java:108)
at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:91)
at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:76)
at cucumber.runtime.formatter.Plugins.createPlugins(Plugins.java:63)
at cucumber.runtime.formatter.Plugins.<init>(Plugins.java:35)
at io.cucumber.junit.CucumberJUnitRunner.<init>(CucumberJUnitRunner.java:96)
at io.cucumber.junit.CucumberJUnitRunnerBuilder.runnerForClass(CucumberJUnitRunnerBuilder.java:11)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:105)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:804)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:575)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.lang.IllegalAccessException: java.lang.Class<com.common.customJSONFormatter.JSONFormatter> is not accessible from java.lang.Class<cucumber.runtime.formatter.PluginFactory>
at java.lang.reflect.Constructor.newInstance(Native Method)
at cucumber.runtime.formatter.PluginFactory.newInstance(PluginFactory.java:104)
... 15 more`

**Comment by lsuski** [comment]
Maybe this class `com.common.customJSONFormatter.JSONFormatter` is not public or has no proper public constructor

**Comment by lsuski** [comment]
from version `7` `cucumber-android` does not support api below 26
