### ISSUE TITLE
cucumber.runtime.CucumberException: No CucumberOptions annotation

### ISSUE THREAD

**Issue by alastorohlin** [cucumber/cucumber-android#53]
Hello, I'm trying to configure an automation project with this tool but I'm getting this error :C 

```
cucumber.runtime.CucumberException: No CucumberOptions annotation
at io.cucumber.junit.AndroidJunitRuntimeOptionsFactory.createRuntimeOptions(AndroidJunitRuntimeOptionsFactory.java:55)
at io.cucumber.junit.CucumberJUnitRunner.<init>(CucumberJUnitRunner.java:83)
at io.cucumber.junit.CucumberJUnitRunnerBuilder.runnerForClass(CucumberJUnitRunnerBuilder.java:11)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
```

I have tried several things but i haven't been able to fix it. Maybe I'm doing something wrong but I don't know what it is. ¿Could someone help me?

This is my app/build.gradle configuration:

```
android {

    defaultConfig {
        multiDexEnabled true
        applicationId "com.example”
        testApplicationId "com.example.test"
        testInstrumentationRunner "io.cucumber.android.runner.CucumberAndroidJUnitRunner"
    }
}

dependencies {

    //Cucumber
    androidTestImplementation "io.cucumber:cucumber-android:4.8.3"

    //UIAutomator
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'

    //OKHttp3
    implementation 'com.squareup.okhttp3:okhttp:3.14.1'

}
```
 src/androidTest/assets/features/SearchUsers.feature:

```
Feature: Search users

    Background: Open App
      Given the user open the app

    Scenario Outline: Check error message
      When the user enters the ID number "<number>" and tap on search
      Then the message "<message>" is visible
      Examples:
        | number   | message                |
        | ABCDE    | The user doesn't exist.|
        | 792486201| The user doesn't exist |
        |          | Internal server error  |
```

Cucumber Options file:

```
package com.example.test;

import io.cucumber.junit.CucumberOptions;

@CucumberOptions(
        glue = "com.example.test.steps",
        plugin = {"pretty"},
        features = "assets/features")

public class Cucumber { }
```
And my step definitions:

```
package com.example.test.steps;

import androidx.test.uiautomator.UiObjectNotFoundException;
import com.example.test.pageObjects.IndexPage;
import org.json.JSONException;
import java.io.IOException;
import io.cucumber.java.en.*;

public class SearchSteps {

    private IndexPage indexPage = new IndexPage();

    @Given("the user open the app")
    public void openApp() {
        indexPage.openApp();
    }

    @When("the user enters the ID number {string} and tap on search")
    public void introduceCredentials(String number) throws UiObjectNotFoundException {
        indexPage.search(number);
    }

    @Then("the message {string} is visible")
    public void checkMessage(String message) {
        indexPage.checkMessage(message);
    }

}

```

**Comment by lsuski** [comment]
`features = "assets/features"` should be `features = "features"`

**Comment by lsuski** [comment]
However it should be the cause. Debug `AndroidJunitRuntimeOptionsFactory.createRuntimeOptions` and check if there are any classes found

**Comment by alastorohlin** [comment]
Hi @lsuski , thanks for your help. I changed `features = "assets/features"` for `features = "features"` but i got the same error.

I debugged the instrumentation tests and got this:

```
I/MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
E/TestRunner: failed: initializationError(io.cucumber.junit.CucumberJUnitRunnerBuilder)
    ----- begin exception -----
E/TestRunner: cucumber.runtime.CucumberException: No CucumberOptions annotation
        at io.cucumber.junit.AndroidJunitRuntimeOptionsFactory.createRuntimeOptions(AndroidJunitRuntimeOptionsFactory.java:55)
        at io.cucumber.junit.CucumberJUnitRunner.<init>(CucumberJUnitRunner.java:83)
        at io.cucumber.junit.CucumberJUnitRunnerBuilder.runnerForClass(CucumberJUnitRunnerBuilder.java:11)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
        at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
        at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
        at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
    ----- end exception -----
I/TestRunner: finished: initializationError(io.cucumber.junit.CucumberJUnitRunnerBuilder)
I/MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
I/TestRunner: run finished: 1 tests, 1 failed, 0 ignored

cucumber.runtime.CucumberException: No CucumberOptions annotation
at io.cucumber.junit.AndroidJunitRuntimeOptionsFactory.createRuntimeOptions(AndroidJunitRuntimeOptionsFactory.java:55)
at io.cucumber.junit.CucumberJUnitRunner.<init>(CucumberJUnitRunner.java:83)
at io.cucumber.junit.CucumberJUnitRunnerBuilder.runnerForClass(CucumberJUnitRunnerBuilder.java:11)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

I/MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
I/MonitoringInstr: waitForActivitiesToComplete() took: 0ms

```

**Comment by alastorohlin** [comment]
I need  `androidTestImplementation "io.cucumber:cucumber-android:4.8.3"` or `androidTestImplementation "io.cucumber:cucumber-picocontainer:4.8.1"` ?

I think the problem is that `cucumber.api.java` Annotations are being requested but the ones from `io.cucumber.java` are imported. With `io.cucumber:cucumber-picocontainer:4.8.1`  i got this message: `No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
`

**Comment by alastorohlin** [comment]
Hello, I made the configuration from the beginning and I was able to get it working. Thanks for the help and sorry for the spam. 🚀

**Comment by JoshuaW-kr** [comment]
> Hello, I made the configuration from the beginning and I was able to get it working. Thanks for the help and sorry for the spam. 🚀

Can you share more of what you did incorect?

**Comment by lsuski** [comment]
The most common error in configuration is that class annotated with `@CucumberOptions` is not placed in `<testApplicationId>` package which by default is `<applicationId>.test` e.g. `com.example.myapp.test`. This testApplicationId can be changed in build.gradle or can be different for different flavours

**Comment by alastorohlin** [comment]
Hi @JoshuaW-kr  I don't remember exactly the problem, because it was a long time ago. But it was in the class with the cucumberOptions annotation.

I had to make changes to the class annotated with @CucumberOptions:

```
package com.example.test;

import io.cucumber.android.runner.CucumberAndroidJUnitRunner;
import io.cucumber.junit.CucumberOptions;

@CucumberOptions(
        features = "features",
        glue = "com.example.steps"
)
public class TestRunner extends CucumberAndroidJUnitRunner {

}
```

Also in the step definitions i had to change `{string}` for `"([^"]*)"`  

I hope this helps you

**Comment by JoshuaW-kr** [comment]
Thank you. I've fixed this issue due to packaging I believe but I'm onto another.

**Comment by alastorohlin** [comment]
What is the other issue? Maybe I have seen it when I was configuring this tool before

**Comment by JoshuaW-kr** [comment]
Here's the error:
```
Caused by: io.cucumber.core.exception.CucumberException: No backends were found. Please make sure you have a backend module on your CLASSPATH.
	at io.cucumber.core.runtime.BackendServiceLoader.get(BackendServiceLoader.java:36)
	at io.cucumber.core.runtime.BackendServiceLoader.get(BackendServiceLoader.java:30)
	at io.cucumber.core.runtime.SingletonRunnerSupplier.createRunner(SingletonRunnerSupplier.java:46)
	at io.cucumber.core.runtime.SingletonRunnerSupplier.get(SingletonRunnerSupplier.java:38)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:243)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.cucumber.core.runtime.Runtime.lambda$run$3(Runtime.java:100)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:101)
	... 7 more
```
I've added all these to my gradle file for deps:
```    
    testImplementation 'io.cucumber:cucumber-junit:6.10.0'
    testImplementation 'io.cucumber:cucumber-java:6.10.0'
    testImplementation 'io.cucumber:cucumber-picocontainer:5.6.0'
    implementation 'io.cucumber:cucumber-android:4.4.1'
```
At this point I've been changing up the version to try and get something to work. I've only added cucumber-junit and cucumber-java due to other answers to this issue I've found online.

**Comment by alastorohlin** [comment]
This issue is new to me haha I just had to use these dependencies to make it  work:

```
      androidTestImplementation 'io.cucumber: cucumber-android: 4.8.3'
      androidTestImplementation 'androidx.test: rules: 1.3.0'
```

Maybe your issue is because you use `implementation` instead of `androidTestImplementation` . Try if those dependencies works for you

**Comment by JoshuaW-kr** [comment]
Unfortunately it's the same error.  What gradle command are you using to run?

**Comment by alastorohlin** [comment]
😞  I use this command for run the tests  `./gradlew cAT`

**Comment by lsuski** [comment]
cucumber-android is for androidTestImplementation and can't be used with different versions of cucumber-java/junit. Add only
```
      androidTestImplementation 'io.cucumber:cucumber-android:4.8.3'
      androidTestImplementation 'io.cucumber:cucumber-picocontainer:4.8.1'

**Comment by certain7** [comment]
> The most common error in configuration is that class annotated with `@CucumberOptions` is not placed in `<testApplicationId>` package which by default is `<applicationId>.test` e.g. `com.example.myapp.test`. This testApplicationId can be changed in build.gradle or can be different for different flavours

this is very important

**Comment by Shubham1dumbhare** [comment]
cucumber.runtime.CucumberException: No backends were found. Please make sure you have a backend module on your CLASSPATH.
	at cucumber.runtime.Runtime.<init>(Runtime.java:80)
	at cucumber.runtime.Runtime.<init>(Runtime.java:69)
	at cucumber.runtime.Runtime.<init>(Runtime.java:65)
	at cucumber.api.junit.Cucumber.createRuntime(Cucumber.java:78)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:58)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at 
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

Hi there can any one help me with :- No Backends were found error...how to resolve it
