### ISSUE TITLE
Cucumber Android not running anymore on R / 30 / Android 11

### ISSUE THREAD

**Issue by childnode** [cucumber/cucumber-android#54]
while testing migration to targetLevel 30 we faced issues running cucumber androidTests on emulator with 30 / android 11.

While our main project just tells us "no tests found"
=> 
on console :connectedVariantAndroidTest with `-e debug true`
```
com.android.build.gradle.internal.testing.ConnectedDevice > No tests found.[Pixel_4_API_30(AVD) - 11] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
```

we have a `CucumberAndroidJUnitRunner` as testInstrumentationRunner
with an
```
@CucumberOptions(
    monochrome = true,
    features = ["features"],
    glue = ["com.example.uitests"],
    tags = ["@fast"]
)
class RunCucumberTest {}
```

----

cuculator fails with
```

cucumber.runtime.CucumberException: java.io.IOException: Failed to create directory /reports
	at cucumber.runtime.formatter.PluginFactory.newInstance(PluginFactory.java:110)
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:91)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:76)
	at cucumber.runtime.formatter.Plugins.createPlugins(Plugins.java:63)
	at cucumber.runtime.formatter.Plugins.<init>(Plugins.java:35)
	at io.cucumber.junit.CucumberJUnitRunner.<init>(CucumberJUnitRunner.java:96)
	at io.cucumber.junit.CucumberJUnitRunnerBuilder.runnerForClass(CucumberJUnitRunnerBuilder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
	at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
	at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
	at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
Caused by: java.io.IOException: Failed to create directory /reports
	at cucumber.runtime.formatter.URLOutputStream.ensureParentDirExists(URLOutputStream.java:53)
	at cucumber.runtime.formatter.URLOutputStream.<init>(URLOutputStream.java:33)
	at cucumber.runtime.formatter.URLOutputStream.<init>(URLOutputStream.java:24)
	at cucumber.runtime.formatter.JUnitFormatter.<init>(JUnitFormatter.java:87)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at cucumber.runtime.formatter.PluginFactory.newInstance(PluginFactory.java:104)
	... 15 more
```

both projects working like a charm on Q/29/android10

- macOs
- SystemImage 30 r6
- Emulator 30.0.14
- SDK PlatformTools 30.0.3
- ABI x86 or x86_64
- targetVariant "Google Play"

**Comment by childnode** [comment]
re-converted the RunCucumberTest to java .. cucumber don't like kotlin?! I fear there is some work needed in https://github.com/cucumber/cucumber-android/blob/master/cucumber-android/src/main/java/io/cucumber/junit/DexClassFinder.java resp. https://github.com/cucumber/cucumber-android/blob/master/cucumber-android/src/main/java/io/cucumber/junit/AndroidJunitRuntimeOptionsFactory.java#L30 ?!

**Comment by lsuski** [comment]
Could you try with cucumber-android 4.8.4 but without `monochrome = true`?

**Comment by childnode** [comment]
ok, I fear there are multiple issues ..

 1. regarding R/30 it didn't changed anything - even plain Java doesn't work here: I see this interesting fatal log in emulator for `androidx.test.services`: 
```
2020-08-27 10:03:52.220 15335-15335/? E/AndroidRuntime: FATAL EXCEPTION: main

    PID: 15335
    java.lang.IllegalArgumentException: Wrong number of arguments; expected 6, got 3
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.test.services.speakeasy.client.ToolConnection$ToolConnectionPostIcs.doCall(ToolConnection.java:197)
        at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:79)
        at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:69)
        at androidx.test.services.shellexecutor.BlockingPublish.getResult(BlockingPublish.java:74)
        at androidx.test.services.shellexecutor.ShellCommandExecutorServer.start(ShellCommandExecutorServer.java:80)
        at androidx.test.services.shellexecutor.ShellMain.main(ShellMain.java:45)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
```
   - 🧑‍🍳 **androidTestUtil androidx.test:orchestrator 1.2.0 -> 1.3.0 fixed it**
https://developer.android.com/jetpack/androidx/releases/test
https://developer.android.com/training/testing/set-up-project

 - 4.8.4 and -monochrome didn't changed anything for me , nontheless it's java or kotlin

------
2. 4.8.2 and 4.8.3 are not working on kotlin  implementation of CucumberAndroidJUnitRunner for Q/29 - actually working on 4.8.1
  - crash log indicates, that once Instrumentation is on kotlin + step definition is java and using cucumber-android > 4.8.1 it fails with things like 
```
cucumber.runtime.CucumberException: Failed to instantiate class your.StepDef
        at cucumber.runtime.java.DefaultJavaObjectFactory.cacheNewInstance(DefaultJavaObjectFactory.java:46)
…
Caused by: cucumber.runtime.CucumberException: Could not create a cucumber expression for 'user swipes {direction}'.
```
Where direction is an (Java)Enum registered in (Java)TypeRegistry.
Again: only change was to switch Instrumentation and CucumberOptions from java to kotlin, not switching anything else
  - 🧇  **Switching TypeRegistry to correct import from `io.cucumber` namespace instead of `cucumber.api` fixes this** 


------
🥊 Punchline: 
- starting kotlin mixed java test classes forces some errors above 4.8.1
  - fixup deprecated Imports!
- for R check your orchestrator

**Comment by lsuski** [comment]
I don't think that kotlin has something to do here, in other words cucumber-android should be fully compatible with kotlin. I'm using kotlin in many projects for years and it works fine with. Currently I'm using cucumber-android 4.8.4 with emulator api 30 and tests execute fine, however I'm using cucumber-picocontainer

**Comment by lsuski** [comment]
Cukeculator does not work on api 30 beacuse reports directory does not exists. It is not necessary to use ` bundle.putString("plugin", getPluginConfigurationString())`, without it it works. It is only for demonstration purposes. Adding `new File(getAbsoluteFilesPath()).mkdirs();` also fixes this issue

**Comment by lsuski** [comment]
I've pushed to master changes in cukeulator. It should work now on Android R, I've also added KotlinSteps to demonstrates that it works with kotlin as well (mixed with java)

**Comment by childnode** [comment]
thank you

**Comment by childnode** [comment]
interesting code finding: https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/testing/SimpleTestRunnable.java;l=326

```
        if (device.getApiLevel() >= 29) {
            // sdcard/Android/media/<package_name> is the only special-cased storage dir, which
            // allows separate shell processes and instrumented tests to both have read/write access
            // without needing to apply external legacy storage flags (which were removed in API 30)
            // or --no-isolated-storage.
            return "/sdcard/Android/media/"
                    + testData.getTestedApplicationId()
                    + "/additional_test_output";
        }
```

Good Advice to use this as a report directory, and yes it works without the `getPluginConfigurationString()` but then you don't get cucumber test reports but those reports generated by JunitInstrumentationRunner on :cAT

I don't see that mkdir is needed as you did in https://github.com/cucumber/cucumber-android/commit/46513872132ed943e06e49ca864bacbfcf687866

…

I'll come up with a proof and fix for that soon once I have cleanly reproduced it.
