### ISSUE TITLE
Fail to run UITest on targetSdkVersion 30

### ISSUE THREAD

**Issue by liweiran10086** [cucumber/cucumber-android#84]
**Describe the bug**
When I change the code in build.gradle to change targetSdkVersion and buildToolsVersion to 30, 

```
    targetSdkVersion = 30
    buildToolsVersion = '30.0.2'
```

and then run UItest on cucumber.cukeulator.test/cucumber.cukeulator.test.CukeulatorAndroidJUnitRunner, it failed to run and crashed
```
$ adb shell am instrument -w -m  --no-window-animation  -e debug false cucumber.cukeulator.test/cucumber.cukeulator.test.CukeulatorAndroidJUnitRunner
Test running failed: Process crashed.
Tests ran to completion.
```

From the Logcat, the error is Unable to find instrumentation info

```
2021-08-03 11:59:10.977 29602-29602/cucumber.cukeulator E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cucumber.cukeulator, PID: 29602
    java.lang.RuntimeException: Unable to find instrumentation info for: ComponentInfo{cucumber.cukeulator.test/cucumber.cukeulator.test.CukeulatorAndroidJUnitRunner}
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6408)
        at android.app.ActivityThread.access$1300(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1885)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7464)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
```
Use adb command to check , it exists.
```
$  adb shell pm list instrumentation
instrumentation:androidx.test.orchestrator/.AndroidTestOrchestrator (target=androidx.test.orchestrator)
instrumentation:cucumber.cukeulator.test/.CukeulatorAndroidJUnitRunner (target=cucumber.cukeulator)
```

**Expected behavior**

It works well if I change back targetSdkVersion to 29, see attched screenshot
<img width="1647" alt="cucumber-android" src="https://user-images.githubusercontent.com/44474610/127956342-ff143d29-6766-445b-a585-9f82c6ca0ca3.png">

**Additional context**
This is the config I use to run the UITest, set the config like this and tap the run All Tests button
<img width="1064" alt="图片" src="https://user-images.githubusercontent.com/44474610/127956846-8cdd733c-50ba-47a0-babd-33f26b7aaab3.png">

**Comment by liweiran10086** [comment]
I'm also using the Gradle steps in https://github.com/cucumber/cucumber-android/blob/main/cukeulator/README.md to reproduce this problem.
at the last step, it failed.
```
$ adb shell am instrument -w cucumber.cukeulator.test/cucumber.cukeulator.test.CukeulatorAndroidJUnitRunner
android.util.AndroidException: INSTRUMENTATION_FAILED: cucumber.cukeulator.test/cucumber.cukeulator.test.CukeulatorAndroidJUnitRunner
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{cucumber.cukeulator.test/cucumber.cukeulator.test.CukeulatorAndroidJUnitRunner}
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1
	at com.android.commands.am.Instrument.run(Instrument.java:519)
	at com.android.commands.am.Am.runInstrument(Am.java:202)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:60)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:396)
```

By the way, the step in Readme should be 
```
./gradlew --parallel :cukeulator:assembleDebugAndroidTest
```

**Comment by liweiran10086** [comment]
The problem only happens when I using simualtor.
After I connect Android studio using a real device, problem solved.
