### ISSUE TITLE
Compose - Cannot run onActivity since Activity has been destroyed already

### ISSUE THREAD

**Issue by dgaillard2** [cucumber/cucumber-android#97]
Hello ✋ 

i was completing all undefined steps, now **all is complete** but i get this error and i don't understand why :
**Java.lang.NulPointerException : Cannot run onActivity since Activity has been destroyed already**

With my android compose project, configure like this : 

```
@CucumberOptions(features = ["features"], glue = ["com.decathlon.printers_presentation.test.steps"])
class PrinterTestOptions {
}
```

```
...
import io.cucumber.java.Before
import io.cucumber.java.en.And
import io.cucumber.java.en.Given
import io.cucumber.java.en.Then
import io.cucumber.java.en.When
import io.cucumber.junit.WithJunitRule
import org.junit.Rule

@Suppress("unused")
@WithJunitRule
class PrinterSearchSteps() {

    @Rule
    @JvmField
    var composeTestRule: ComposeContentTestRule = createComposeRule()

    private val uiState = PrintersListUiState.DevicesListState()

    @Before
    fun before() {
        composeTestRule.setContent {
            val state = remember {
                uiState
            }
            val onSearchChange: (String) -> Unit = {

            }
            val onClearTextClick = {

            }
            val onClick: (String) -> Unit = {

            }
            VitaminTheme {
                PrintersListScreen(
                    state,
                    onSearchChange,
                    onClearTextClick,
                    onClick
                )
            }
        }
    }

    @Given("Benjamin is authenticated in the warehouse {string}")
    fun xxIsAuthenticatedToWarehouseYY(warehouse: String?) {
    }

    @When("he retrieves the list of printers")
    fun whenGetPrintersIsSuccess() {
    }

    @And("the following printers exist:")
    fun printersExists(arg0: MutableList<String>) {
    }

    @And("the following printers are listed")
    fun printersListed() {
    }

    @Then("the printer list is retrieved successfully")
    fun printersRetrievedSuccessfully() {
    }
}
```

I want to use createComposeRule and avoid specifying activity because it s a module without activity and with only composable, so createComposeRule seems all right to do this but i got this error

Do you have any idea if it s normal ?

**Comment by lsuski** [comment]
Could you provide full stacktrace?

**Comment by dgaillard2** [comment]
Here is the stacktrace 

```
java.lang.NullPointerException: Cannot run onActivity since Activity has been destroyed already
at androidx.test.internal.util.Checks.checkNotNull(Checks.java:45)
at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:658)
at androidx.test.core.app.ActivityScenario$$Lambda$4.run(ActivityScenario.java:652)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Thank you

**Comment by dgaillard2** [comment]
For information, if i remove from my build.gradle.kts : 

    ```
    testInstrumentationRunner = "io.cucumber.android.runner.CucumberAndroidJUnitRunner"
        testApplicationId = "com.decathlon.printers_presentation"
```

And if i add

**Comment by dgaillard2** [comment]
I just solved my problem

I replaced @Before with JUnit one : 

Replaced 

`import io.cucumber.java.en.Before`

to

`import org.junit.Before`
