### ISSUE TITLE
Compose Junit rules support issue

### ISSUE THREAD

**Issue by tonyage** [cucumber/cucumber-android#99]
Hello big fan of the library, I am having issues getting cucumber tests to play nicely with compose test library. As outlined in the Junit rules support in the readme. Using Koin instead of hilt I am injecting a single class that holds my compose rule and activity scenario, but I am getting this error

> java.lang.IllegalStateException: Test not setup properly. Use a ComposeTestRule in your test to be able to interact with composables
at androidx.compose.ui.test.junit4.ComposeRootRegistry_androidKt.ensureComposeRootRegistryIsSetUp(ComposeRootRegistry.android.kt:259)
at androidx.compose.ui.test.junit4.ComposeRootRegistry_androidKt.waitForComposeRoots(ComposeRootRegistry.android.kt:266)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule.waitForIdle(AndroidComposeTestRule.android.kt:282)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule.access$waitForIdle(AndroidComposeTestRule.android.kt:150)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidTestOwner.getRoots(AndroidComposeTestRule.android.kt:476)
at androidx.compose.ui.test.TestContext.getAllSemanticsNodes$ui_test_release(TestOwner.kt:95)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNodes$ui_test_release(SemanticsNodeInteraction.kt:79)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:145)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:96)
at androidx.compose.ui.test.AndroidAssertions_androidKt.checkIsDisplayed(AndroidAssertions.android.kt:29)
at androidx.compose.ui.test.AssertionsKt.assertIsDisplayed(Assertions.kt:33)
at com.tonyage.app.test.AllSteps.theUserIsAtTheEULAScreen(AllSteps.kt:27)
at ✽.the user is at the EULA screen(file:features/test.feature:6)

My runner inflates a TestApplication that handles the injection 
Robot.kt looks like this
```
@WithJunitRule
class Robot {
    @get:Rule val composeTestRule = createEmptyTestRule()
    private var scenario:ActivityScenario<*>? = null

    fun launch(intent:Intent){
        scenario = ActivityScenario.launch<Activity>(intent)
        scenario?.onActivity {
             assertNotNull(it)
        }
    }

    @After
    fun close(){
        scenario?.close()
    }
}
```
And AllSteps looks something like
```
class KotlinSteps(val robot: Robot):SemanticsNodeInteractionsProvider by robot.composeTestRule {

    @Given("the app starts")
    fun theAppStarts() {
         robot.apply {
              launch(splashIntent)
         }
    }
    @Given("the user sees a EULA")
    fun theUserSeesAEULA() {
         robot.apply {
              launch(eulaIntent)
              onNodeWithText("Agree").performClick()   <------ exception occurs here
         } 
    }
} 
```
Any advice on how to remedy this? What am I missing here?

**Comment by lsuski** [comment]
Is the Robot class in glue package? It has to be there to be visible by cucumber. Also I'm not sure how koin is doing something here. In tests cucumber is responsible for creating test classes and injecting deps in them. Koin can be used only for classes injected in application code.  So Robot and steps classes must be created and injected by cucumber, e.g. using cucumber-picocontainer
